version: '3'

networks:
  default:

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: on-failure
    hostname: 'gitlab'
    depends_on:
      - postgresql
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:1080'

        postgresql['enable'] = false
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_username'] = 'postgres'
        gitlab_rails['db_password'] = ''

        gitlab_rails['gitlab_shell_ssh_port'] = 1022
    ports:
      - '1080:1080'
      - '1022:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      - default

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: on-failure
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './runner/config:/etc/gitlab-runner'
    networks:
      - default

  postgresql:
    image: 'postgres:11.1'
    volumes:
      - './postgresql/data:/var/lib/postgresql/data'
    networks:
      - default

  pg_admin:
    image: 'dpage/pgadmin4'
    ports:
      - 2080:80
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@localhost'
      PGADMIN_DEFAULT_PASSWORD: '0000'
    volumes:
      - './pgadmin:/var/lib/pgadmin'
    networks:
      - default

